// ── Temporary GRN Data ─────────────────────────────────────────────────────────
// Replace API calls with this data for local development / UI testing.

import type { PORecord, GRNRecord } from './types';

export const TEMP_PO_LIST: PORecord[] = [
  {
    po_basic_sno: 1001,
    po_no: 'PO-2026-001',
    pr_basic_sno: 201,
    pr_no: 'PR-2026-021',
    vendor_sno: 11,
    vendor_name: 'Agarwal Traders Pvt Ltd',
    po_date: '2026-03-15',
    required_date: '2026-04-10',
    delivery_address: '12, Industrial Area, Phase II, Chandigarh – 160002',
    terms_conditions: 'Payment within 30 days of delivery',
    purpose: 'Office stationery procurement',
    com_sno: 1,
    com_name: 'STPL Corp',
    div_sno: 2,
    div_name: 'Admin Division',
    brn_sno: 3,
    brn_name: 'Head Office',
    dept_sno: 4,
    dept_name: 'Administration',
    grn_status: 'Pending',
    total_amount: 45000,
    items: [
      {
        po_item_sno: 5001,
        prod_sno: 301,
        prod_name: 'A4 Copier Paper (500 sheets)',
        specification: '75 GSM, White',
        ordered_qty: 100,
        received_qty: 0,
        pending_qty: 100,
        unit_name: 'Ream',
        unit_price: 250,
        total_amount: 25000,
      },
      {
        po_item_sno: 5002,
        prod_sno: 302,
        prod_name: 'Ballpoint Pen (Blue)',
        specification: 'Medium tip, 0.7mm',
        ordered_qty: 200,
        received_qty: 0,
        pending_qty: 200,
        unit_name: 'Pcs',
        unit_price: 10,
        total_amount: 2000,
      },
      {
        po_item_sno: 5003,
        prod_sno: 303,
        prod_name: 'Stapler',
        specification: 'Heavy duty, 24/6 pins',
        ordered_qty: 20,
        received_qty: 0,
        pending_qty: 20,
        unit_name: 'Pcs',
        unit_price: 150,
        total_amount: 3000,
      },
    ],
  },
  {
    po_basic_sno: 1002,
    po_no: 'PO-2026-002',
    pr_basic_sno: 202,
    pr_no: 'PR-2026-018',
    vendor_sno: 12,
    vendor_name: 'National Electronics Supply Co.',
    po_date: '2026-03-20',
    required_date: '2026-04-15',
    delivery_address: '45, Electronics Hub, Sector 18, Noida – 201301',
    terms_conditions: '50% advance, balance on delivery',
    purpose: 'IT equipment for new branch setup',
    com_sno: 1,
    com_name: 'STPL Corp',
    div_sno: 3,
    div_name: 'IT Division',
    brn_sno: 5,
    brn_name: 'Noida Branch',
    dept_sno: 7,
    dept_name: 'IT Department',
    grn_status: 'Partial',
    total_amount: 320000,
    items: [
      {
        po_item_sno: 5010,
        prod_sno: 310,
        prod_name: 'Dell Laptop (Core i5)',
        specification: '8GB RAM, 512GB SSD, Windows 11 Pro',
        ordered_qty: 10,
        received_qty: 6,
        pending_qty: 4,
        unit_name: 'Nos',
        unit_price: 55000,
        total_amount: 550000,
      },
      {
        po_item_sno: 5011,
        prod_sno: 311,
        prod_name: 'USB-C Docking Station',
        specification: '4K HDMI, 3×USB-A, Ethernet',
        ordered_qty: 10,
        received_qty: 6,
        pending_qty: 4,
        unit_name: 'Nos',
        unit_price: 3500,
        total_amount: 35000,
      },
      {
        po_item_sno: 5012,
        prod_sno: 312,
        prod_name: 'Wireless Mouse',
        specification: '2.4GHz, ergonomic design',
        ordered_qty: 15,
        received_qty: 15,
        pending_qty: 0,
        unit_name: 'Nos',
        unit_price: 800,
        total_amount: 12000,
      },
    ],
  },
  {
    po_basic_sno: 1003,
    po_no: 'PO-2026-003',
    pr_basic_sno: 203,
    pr_no: 'PR-2026-015',
    vendor_sno: 13,
    vendor_name: 'Hindustan Safety Products',
    po_date: '2026-03-25',
    required_date: '2026-04-05',
    delivery_address: '8, Industrial Estate, Pune – 411019',
    terms_conditions: 'Net 15 days',
    purpose: 'Safety gear for factory floor workers',
    com_sno: 1,
    com_name: 'STPL Corp',
    div_sno: 4,
    div_name: 'Manufacturing',
    brn_sno: 6,
    brn_name: 'Pune Plant',
    dept_sno: 9,
    dept_name: 'Safety & Compliance',
    grn_status: 'Received',
    total_amount: 78500,
    items: [
      {
        po_item_sno: 5020,
        prod_sno: 320,
        prod_name: 'Safety Helmet (Yellow)',
        specification: 'IS 2925 certified, adjustable ratchet',
        ordered_qty: 50,
        received_qty: 50,
        pending_qty: 0,
        unit_name: 'Nos',
        unit_price: 350,
        total_amount: 17500,
      },
      {
        po_item_sno: 5021,
        prod_sno: 321,
        prod_name: 'Safety Shoes (Steel Toe)',
        specification: 'Size 6–10, leather upper',
        ordered_qty: 30,
        received_qty: 30,
        pending_qty: 0,
        unit_name: 'Pairs',
        unit_price: 1200,
        total_amount: 36000,
      },
      {
        po_item_sno: 5022,
        prod_sno: 322,
        prod_name: 'High-Vis Jacket',
        specification: 'ANSI Class 2, orange with reflective strips',
        ordered_qty: 50,
        received_qty: 50,
        pending_qty: 0,
        unit_name: 'Nos',
        unit_price: 500,
        total_amount: 25000,
      },
    ],
  },
  {
    po_basic_sno: 1004,
    po_no: 'PO-2026-004',
    pr_basic_sno: 204,
    pr_no: 'PR-2026-031',
    vendor_sno: 14,
    vendor_name: 'Sunrise Chemicals Ltd',
    po_date: '2026-04-01',
    required_date: '2026-04-20',
    delivery_address: '21, Chemical Zone, Vapi – 396195',
    terms_conditions: 'Payment within 45 days',
    purpose: 'Cleaning chemicals for all branches',
    com_sno: 1,
    com_name: 'STPL Corp',
    div_sno: 2,
    div_name: 'Admin Division',
    brn_sno: 3,
    brn_name: 'Head Office',
    dept_sno: 4,
    dept_name: 'Facilities Management',
    grn_status: 'Pending',
    total_amount: 32000,
    items: [
      {
        po_item_sno: 5030,
        prod_sno: 330,
        prod_name: 'Floor Cleaner Concentrate',
        specification: '5L can, citrus fragrance',
        ordered_qty: 40,
        received_qty: 0,
        pending_qty: 40,
        unit_name: 'Can',
        unit_price: 400,
        total_amount: 16000,
      },
      {
        po_item_sno: 5031,
        prod_sno: 331,
        prod_name: 'Hand Sanitizer (500ml)',
        specification: '70% isopropyl alcohol, pump dispenser',
        ordered_qty: 100,
        received_qty: 0,
        pending_qty: 100,
        unit_name: 'Btl',
        unit_price: 160,
        total_amount: 16000,
      },
    ],
  },
];

export const TEMP_GRN_LIST: GRNRecord[] = [
  // GRNs for PO-2026-002 (Partial)
  {
    grn_basic_sno: 9001,
    grn_no: 'GRN-2026-001',
    po_basic_sno: 1002,
    po_no: 'PO-2026-002',
    vendor_sno: 12,
    vendor_name: 'National Electronics Supply Co.',
    received_date: '2026-03-28',
    received_by: 'USR-07',
    received_by_name: 'Ramesh Kumar',
    doc_ref_no: 'DC/NES/2026/143',
    vehicle_no: 'DL 1C 3456',
    challan_no: 'CH-NES-2026-143',
    remarks: 'First batch received. Remaining 4 laptops and docking stations expected next week.',
    status: 'Approved',
    created_at: '2026-03-28T11:30:00',
    items: [
      {
        grn_item_sno: 8001,
        po_item_sno: 5010,
        prod_sno: 310,
        prod_name: 'Dell Laptop (Core i5)',
        specification: '8GB RAM, 512GB SSD, Windows 11 Pro',
        ordered_qty: 10,
        received_qty: 6,
        rejected_qty: 0,
        unit_name: 'Nos',
        condition: 'Good',
        remarks: 'All units verified and in good condition',
      },
      {
        grn_item_sno: 8002,
        po_item_sno: 5011,
        prod_sno: 311,
        prod_name: 'USB-C Docking Station',
        specification: '4K HDMI, 3×USB-A, Ethernet',
        ordered_qty: 10,
        received_qty: 6,
        rejected_qty: 0,
        unit_name: 'Nos',
        condition: 'Good',
        remarks: '',
      },
      {
        grn_item_sno: 8003,
        po_item_sno: 5012,
        prod_sno: 312,
        prod_name: 'Wireless Mouse',
        specification: '2.4GHz, ergonomic design',
        ordered_qty: 15,
        received_qty: 15,
        rejected_qty: 0,
        unit_name: 'Nos',
        condition: 'Good',
        remarks: 'Full quantity received',
      },
    ],
  },
  // GRNs for PO-2026-003 (Fully Received)
  {
    grn_basic_sno: 9002,
    grn_no: 'GRN-2026-002',
    po_basic_sno: 1003,
    po_no: 'PO-2026-003',
    vendor_sno: 13,
    vendor_name: 'Hindustan Safety Products',
    received_date: '2026-04-02',
    received_by: 'USR-09',
    received_by_name: 'Sunil Patil',
    doc_ref_no: 'DC/HSP/2026/088',
    vehicle_no: 'MH 14 AB 7890',
    challan_no: 'CH-HSP-2026-088',
    remarks: 'Complete order received in excellent condition.',
    status: 'Approved',
    created_at: '2026-04-02T09:15:00',
    items: [
      {
        grn_item_sno: 8010,
        po_item_sno: 5020,
        prod_sno: 320,
        prod_name: 'Safety Helmet (Yellow)',
        specification: 'IS 2925 certified, adjustable ratchet',
        ordered_qty: 50,
        received_qty: 50,
        rejected_qty: 0,
        unit_name: 'Nos',
        condition: 'Good',
        remarks: '',
      },
      {
        grn_item_sno: 8011,
        po_item_sno: 5021,
        prod_sno: 321,
        prod_name: 'Safety Shoes (Steel Toe)',
        specification: 'Size 6–10, leather upper',
        ordered_qty: 30,
        received_qty: 28,
        rejected_qty: 2,
        unit_name: 'Pairs',
        condition: 'Partial',
        remarks: '2 pairs rejected due to stitching defect. Replacement to be arranged.',
      },
      {
        grn_item_sno: 8012,
        po_item_sno: 5022,
        prod_sno: 322,
        prod_name: 'High-Vis Jacket',
        specification: 'ANSI Class 2, orange with reflective strips',
        ordered_qty: 50,
        received_qty: 50,
        rejected_qty: 0,
        unit_name: 'Nos',
        condition: 'Good',
        remarks: '',
      },
    ],
  },
];

/** Returns GRNs filtered for a given PO. */
export const getTempGRNsForPO = (po_basic_sno: number): GRNRecord[] =>
  TEMP_GRN_LIST.filter(g => g.po_basic_sno === po_basic_sno);
